package com.skidsense.mobile.api

import java.security.KeyPairGenerator
import java.security.spec.MGF1ParameterSpec
import java.util.Base64
import javax.crypto.Cipher
import javax.crypto.spec.GCMParameterSpec
import javax.crypto.spec.OAEPParameterSpec
import javax.crypto.spec.PSource
import javax.crypto.spec.SecretKeySpec
import kotlin.test.Test
import kotlin.test.assertEquals
import kotlin.test.assertTrue

/**
 * The login password envelope (spec §12), against a key generated by the JDK
 * and decrypted with the JDK — deliberately *not* with the same library that
 * encrypted it, so the test pins the actual wire format rather than the
 * round trip of one implementation.
 */
class PasswordEnvelopeJvmTest {
    private val random = java.security.SecureRandom()
    private val keyPair = KeyPairGenerator.getInstance("RSA").apply { initialize(2048, random) }.generateKeyPair()

    private fun decryptV2(envelope: String, label: String): String {
        val parts = envelope.split(".")
        assertEquals(4, parts.size, "v2 envelope has four segments")
        assertEquals("v2", parts[0])
        val decoder = Base64.getDecoder()
        val cipher = Cipher.getInstance("RSA/ECB/OAEPPadding")
        cipher.init(
            Cipher.DECRYPT_MODE,
            keyPair.private,
            OAEPParameterSpec("SHA-256", "MGF1", MGF1ParameterSpec.SHA256, PSource.PSpecified(label.encodeToByteArray()))
        )
        val aesKey = cipher.doFinal(decoder.decode(parts[1]))
        assertEquals(32, aesKey.size)

        val gcm = Cipher.getInstance("AES/GCM/NoPadding")
        gcm.init(Cipher.DECRYPT_MODE, SecretKeySpec(aesKey, "AES"), GCMParameterSpec(128, decoder.decode(parts[2])))
        gcm.updateAAD("password-v2:kid-7".encodeToByteArray())
        return gcm.doFinal(decoder.decode(parts[3])).decodeToString()
    }

    @Test
    fun envelopeOpensWithTheV2Label() {
        val pem = "-----BEGIN PUBLIC KEY-----\n" +
            Base64.getMimeEncoder(64, "\n".toByteArray()).encodeToString(keyPair.public.encoded) +
            "\n-----END PUBLIC KEY-----\n"
        val envelope = PasswordEnvelope.encrypt("s3cret-密码", pem, "kid-7")
        assertEquals("s3cret-密码", decryptV2(envelope, "password-v2"))
    }

    @Test
    fun aWrongLabelOrKidDoesNotOpen() {
        val pem = "-----BEGIN PUBLIC KEY-----\n" +
            Base64.getMimeEncoder(64, "\n".toByteArray()).encodeToString(keyPair.public.encoded) +
            "\n-----END PUBLIC KEY-----\n"
        val envelope = PasswordEnvelope.encrypt("x", pem, "kid-7")
        // Same RSA key, wrong OAEP label: the AES key never comes out.
        val failed = runCatching { decryptV2(envelope, "password-v1") }
        assertTrue(failed.isFailure, "the label is part of OAEP, not decoration")
    }

    @Test
    fun envelopeCarriesAFreshKeyAndNonceEveryTime() {
        val pem = "-----BEGIN PUBLIC KEY-----\n" +
            Base64.getMimeEncoder(64, "\n".toByteArray()).encodeToString(keyPair.public.encoded) +
            "\n-----END PUBLIC KEY-----\n"
        val a = PasswordEnvelope.encrypt("same", pem, "kid-7").split(".")
        val b = PasswordEnvelope.encrypt("same", pem, "kid-7").split(".")
        assertTrue(!a[1].contentEquals(b[1]), "wrapped AES key differs")
        assertTrue(!a[2].contentEquals(b[2]), "nonce differs")
        assertTrue(!a[3].contentEquals(b[3]), "ciphertext differs")
        assertEquals("same", decryptV2(a.joinToString("."), "password-v2"))
        assertEquals("same", decryptV2(b.joinToString("."), "password-v2"))
    }

    @Test
    fun envelopeIsStandardBase64NotUrlSafe() {
        val pem = "-----BEGIN PUBLIC KEY-----\n" +
            Base64.getMimeEncoder(64, "\n".toByteArray()).encodeToString(keyPair.public.encoded) +
            "\n-----END PUBLIC KEY-----\n"
        // A long password makes the ciphertext very likely to hit a byte whose
        // standard base64 form contains '+', which Go's decoder accepts and a
        // url-safe alphabet would not produce.
        val envelope = PasswordEnvelope.encrypt("a".repeat(600) + "汉字", pem, "kid-7")
        assertTrue(!envelope.contains('-') && !envelope.contains('_'), envelope.take(80))
        assertEquals("a".repeat(600) + "汉字", decryptV2(envelope, "password-v2"))
    }

    @Test
    fun fixedKeyMaterialsProduceTheReferenceLayout() {
        // Not a known-answer vector (RSA-OAEP is randomised); this pins the
        // shape: v2.<wrapped 256 bytes>.<nonce 12>.<ciphertext‖tag>.
        val pem = "-----BEGIN PUBLIC KEY-----\n" +
            Base64.getMimeEncoder(64, "\n".toByteArray()).encodeToString(keyPair.public.encoded) +
            "\n-----END PUBLIC KEY-----\n"
        val parts = PasswordEnvelope.encrypt("pw", pem, "kid").split(".")
        val decoder = Base64.getDecoder()
        assertEquals(256, decoder.decode(parts[1]).size, "2048-bit RSA wraps a 32-byte key in 256 bytes")
        assertEquals(12, decoder.decode(parts[2]).size)
        assertEquals(2 + 16, decoder.decode(parts[3]).size, "ciphertext plus a 16-byte GCM tag")
        assertEquals("pw".length + 16, decoder.decode(parts[3]).size, "ciphertext plus a 16-byte GCM tag")
    }
}
